### PR TITLE
fix: cookies usage on edge functions.

### LINKED ISSUE #3: Error: Invariant: Method expects to have requestAsyncStorage, none available
Hey, I cloned the repo, followed the readme, but i see this error? Any inputs ?

I have already searched online without any luck

Also, is it mandatory to start the supabase local stack ?

```
Error: Invariant: Method expects to have requestAsyncStorage, none available
    at Object.cookies (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/headers.js:46:15)
    at NextRouteHandlerAuthStorageAdapter.getCookie (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.7.2_@supabase+supabase-js@2.26.0/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:230:42)
    at NextRouteHandlerAuthStorageAdapter.getItem (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+auth-helpers-shared@0.4.1_@supabase+supabase-js@2.26.0/node_modules/@supabase/auth-helpers-shared/dist/index.js:261:28)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:151:37)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:59:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:41:12)
    at getItemAsync (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:150:38)
    at SupabaseAuthClient.eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1356:73)
Error: Invariant: Method expects to have requestAsyncStorage, none available
    at Object.cookies (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.7-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/headers.js:46:15)
    at NextRouteHandlerAuthStorageAdapter.getCookie (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.7.2_@supabase+supabase-js@2.26.0/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:230:42)
    at NextRouteHandlerAuthStorageAdapter.getItem (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+auth-helpers-shared@0.4.1_@supabase+supabase-js@2.26.0/node_modules/@supabase/auth-helpers-shared/dist/index.js:261:28)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:151:37)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:59:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:41:12)
    at getItemAsync (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:150:38)
    at SupabaseAuthClient.eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/@supabase+gotrue-js@2.39.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:793:75)
```

### PR DESCRIPTION
**Pull request by thorwebdev**
Fixes #3 

It's very important at what point you call the `cookies` method for things to work correctly. 

So rather than handing the `cookies` method to the supabase client, we need to extract the value first, and then hand the supabase client a function that retrieves that value, e.g.:

```js
'use server'
import { createServerActionClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { Database } from '@/lib/db_types'

const cookieStore = cookies()
const supabase = createServerActionClient<Database>({
  cookies: () => cookieStore
})
```

### CODE REVIEW

**Comment by bradbitler** [comment]
thank you, this worked for me too.

**Comment by wojtekKrol** [comment]
This is not working for me, 

im trying to call it inside of context.ts which later is passed to trpc context

```typescript
// inner context
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { inferAsyncReturnType } from '@trpc/server'
import { FetchCreateContextFnOptions } from '@trpc/server/src/adapters/fetch'
import { cookies } from 'next/headers'

import { Database } from '@/database/databaseType'

// outer context
export async function createContextInner() {
  const cookieStore = cookies()
  const supabase = createRouteHandlerClient<Database>({
    cookies: () => cookieStore,
  })

  return {
    supabase,
  }
}

export async function createContext(opts: FetchCreateContextFnOptions) {
  const contextInner = await createContextInner()

  return {
    ...contextInner,
    req: opts.req,
    res: opts.resHeaders,
  }
}
export type Context = inferAsyncReturnType<typeof createContextInner>

```

```typescript

const t = initTRPC.context<Context>().create({
  // const t = initTRPC.create({
  transformer: superjson,
  errorFormatter({ shape, error }) {
    return {
      ...shape,
      data: {
        ...shape.data,
        zodError:
          error.cause instanceof ZodError ? error.cause.flatten() : null,
      },
    }
  },
})
```

Still getting

```shell
Error: Invariant: cookies() expects to have requestAsyncStorage, none available.
    at cookies (webpack-internal:///(rsc)/./node_modules/next/dist/client/components/headers.js:50:15)
    at createContextInner (webpack-internal:///(rsc)/./src/server/context.ts:15:78)
    at initServerClient (webpack-internal:///(rsc)/./src/server/index.ts:19:94)
    at eval (webpack-internal:///(rsc)/./src/app/_utils/api/serverClient.ts:7:79)
    at (rsc)/./src/app/_utils/api/serverClient.ts (/home/wkrol/NextBase-DevKit/.next/server/app/(routes)/(account)/todo/page.js:4453:1)
    at __webpack_require__ (/home/wkrol/NextBase-DevKit/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/(routes)/(account)/todo/page.tsx:10:85)
    at (rsc)/./src/app/(routes)/(account)/todo/page.tsx (/home/wkrol/NextBase-DevKit/.next/server/app/(routes)/(account)/todo/page.js:4340:1)
    at Function.__webpack_require__ (/home/wkrol/NextBase-DevKit/.next/server/webpack-runtime.js:33:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by nicitaacom** [comment]
> This is not working for me,
> 
> im trying to call it inside of context.ts which later is passed to trpc context
> 
> ```ts
> // inner context
> import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
> import { inferAsyncReturnType } from '@trpc/server'
> import { FetchCreateContextFnOptions } from '@trpc/server/src/adapters/fetch'
> import { cookies } from 'next/headers'
> 
> import { Database } from '@/database/databaseType'
> 
> // outer context
> export async function createContextInner() {
>   const cookieStore = cookies()
>   const supabase = createRouteHandlerClient<Database>({
>     cookies: () => cookieStore,
>   })
> 
>   return {
>     supabase,
>   }
> }
> 
> export async function createContext(opts: FetchCreateContextFnOptions) {
>   const contextInner = await createContextInner()
> 
>   return {
>     ...contextInner,
>     req: opts.req,
>     res: opts.resHeaders,
>   }
> }
> export type Context = inferAsyncReturnType<typeof createContextInner>
> ```
> 
> ```ts
> const t = initTRPC.context<Context>().create({
>   // const t = initTRPC.create({
>   transformer: superjson,
>   errorFormatter({ shape, error }) {
>     return {
>       ...shape,
>       data: {
>         ...shape.data,
>         zodError:
>           error.cause instanceof ZodError ? error.cause.flatten() : null,
>       },
>     }
>   },
> })
> ```
> 
> Still getting
> 
> ```shell
> Error: Invariant: cookies() expects to have requestAsyncStorage, none available.
>     at cookies (webpack-internal:///(rsc)/./node_modules/next/dist/client/components/headers.js:50:15)
>     at createContextInner (webpack-internal:///(rsc)/./src/server/context.ts:15:78)
>     at initServerClient (webpack-internal:///(rsc)/./src/server/index.ts:19:94)
>     at eval (webpack-internal:///(rsc)/./src/app/_utils/api/serverClient.ts:7:79)
>     at (rsc)/./src/app/_utils/api/serverClient.ts (/home/wkrol/NextBase-DevKit/.next/server/app/(routes)/(account)/todo/page.js:4453:1)
>     at __webpack_require__ (/home/wkrol/NextBase-DevKit/.next/server/webpack-runtime.js:33:43)
>     at eval (webpack-internal:///(rsc)/./src/app/(routes)/(account)/todo/page.tsx:10:85)
>     at (rsc)/./src/app/(routes)/(account)/todo/page.tsx (/home/wkrol/NextBase-DevKit/.next/server/app/(routes)/(account)/todo/page.js:4340:1)
>     at Function.__webpack_require__ (/home/wkrol/NextBase-DevKit/.next/server/webpack-runtime.js:33:43)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

For me as well
```
Collecting page data  ..Error: Invariant: cookies() expects to have requestAsyncStorage, none available
```

**Comment by nicitaacom** [comment]
is any updates how fix it?

If somebody fixed it - please share your solution here with code

**Pull request merged**
